In [3]:
pip install pennylane --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 3.7 MB/s  0:00:02m0:00:0100:01
  Attempting uninstall: pennylane
    Found existing installation: pennylane 0.44.0
    Uninstalling pennylane-0.44.0:
      Successfully uninstalled pennylane-0.44.0
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip show pennylane


Name: pennylane
Version: 0.44.1
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: 
Author: 
Author-email: 
License-Expression: Apache-2.0
Location: /opt/miniconda3/lib/python3.12/site-packages
Requires: appdirs, autograd, autoray, cachetools, diastatic-malt, gast, networkx, numpy, packaging, pennylane-lightning, requests, rustworkx, scipy, tomlkit, typing_extensions
Required-by: pennylane_lightning
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pennylane as qml

In [4]:
qml.__version__

'0.44.1'

In [5]:
dev = qml.device('default.qubit', wires = 2)

In [6]:
def qc():
    qml.PauliX(wires=0)
    # wires = 0 representa el qubit sobre el que actua el operador
    qml.Hadamard(wires=0)
    return qml.state()

In [ ]:
qcirc = qml.QNode(qc,dev)
qcirc()

#The result of assembling a circuit function and a device is known in Pennylane as a Quantum Node

array([ 0.70710678+0.j,  0.        +0.j, -0.70710678+0.j,  0.        +0.j])

METODO 2

In [21]:
@qml.qnode(dev)
def qcirc():
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.state()

In [26]:
qcirc()

array([ 0.70710678+0.j, -0.70710678+0.j])

In [25]:
print(qml.draw(qcirc)())

0: ──X──H─┤  State


In [14]:
dev = qml.device('default.qubit', wires = 1)

@qml.qnode(dev)
#podemos incluir parametros en el circuito
def qcirc1(theta):
    qml.RX(theta,wires = 0)
    return qml.state()

In [ ]:
#tambien podriamos usar bucles, condicinales...

In [15]:
print(qml.draw(qcirc1)(theta = 2))

0: ──RX(2.00)─┤  State


In [29]:
@qml.qnode(dev)
def qcirc2():
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.probs()

In [30]:
qcirc2()

array([0.5, 0.5])

In [52]:
@qml.qnode(dev)
def qcirc3():
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.sample()

new_qnode = qml.set_shots(qcirc3, shots = 16)

In [57]:
new_qnode()

array([[0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 0]])

In [49]:
@qml.set_shots(shots=10)
@qml.qnode(dev)
def qcirc4():
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.sample()

In [51]:
qcirc4()

array([[0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0]])

In [5]:
pip install pennylane-qiskit

Note: you may need to restart the kernel to use updated packages.


In [6]:
dev = qml.device('qiskit.aer', wires = 2)

In [9]:
@qml.qnode(dev)
def qcirc():
    qml.Hadamard(wires = 0)
    return qml.probs(wires = 0)

In [10]:
qcirc()

array([0.52441406, 0.47558594])

In [ ]:
#el resultado es array([0.52441406, 0.47558594]) por lo que es empirico

In [11]:
# para obtener el vector de estado

dev = qml.device('qiskit.aer', wires = 2, backend = 'aer_simulator_statevector', shots = None)

In [14]:
@qml.qnode(dev)
def qcirc():
    qml.Hadamard(wires = 0)
    return qml.state()

In [15]:
qcirc()

array([0.70710678+0.j, 0.        +0.j, 0.70710678+0.j, 0.        +0.j])